name: "ci"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Spec:
    uses: "./.github/workflows/module_ci.yml"
    secrets: "inherit"

#  Acceptance:
#    needs: Spec
#    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@main"
#    secrets: "inherit"
